Repository codeing999/CLIPs-backend, pull requests merged in 2022-08, with the labels that each got.

#1 PR : 프로젝트 기본 틀 작성
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/layers/routers/index.js
  src/sequelize/config/config.js
  src/sequelize/models/index.js
Labels: add

#2 PR : 프로젝트 기본 틀 작성.
  README.md
  package-lock.json
  package.json
  src/app.js
  src/layers/routers/index.js
  src/sequelize/config/config.js
  src/sequelize/models/index.js
Labels: add, bugfix

#3 PR : add models/promise.js, models/user.js
  src/sequelize/config/config.js
  src/sequelize/models/index.js
  src/sequelize/models/promise.js
  src/sequelize/models/user.js
Labels: add

#7 Add and Create promise related api
  src/db-init.js
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/index.js
  src/layers/routers/promise.router.js
  src/layers/services/promise.service.js
Labels: documentation, add

#9 PR : 문서 작성.
  README.md
  docs/CRUD.md
  docs/Sequelize.md
  docs/coding_convention.md
  jest.config.json
  package.json
Labels: documentation

#11 modify readme.md
  README.md
Labels: documentation

#13 Modified promise model && Added features from promise related APIs
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
  src/sequelize/models/promise.js
Labels: enhancement, add

#26 깃 플로우 변경 단계에서 충돌 확인 위해 한번 main에 merge
  .gitignore
  README.md
  docs/CRUD.md
  docs/Sequelize.md
  docs/coding_convention.md
  jest.config.json
  package-lock.json
  package.json
  src/app.js
  src/db-init.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/main.controller.js
  src/layers/controllers/prac.js
  src/layers/controllers/promise.controller.js
  src/layers/middlewares/auth.middleware.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/main.repository.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/auth.router.js
  src/layers/routers/index.js
  src/layers/routers/main.router.js
  src/layers/routers/promise.router.js
  src/layers/services/auth.service.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/sequelize/config/config.js
  src/sequelize/models/index.js
  src/sequelize/models/promise.js
  src/sequelize/models/user.js
Labels: add
