Repository codeing999/CLIPs-backend, pull requests merged in 2022-09, with the labels that each got.

#34 PR : modify documents
  README.md
  docs/convention.md
  docs/git.md
Labels: documentation

#41 crawling error#40
  .gitignore
  html.txt
  package-lock.json
  package.json
  src/layers/controllers/main.controller.js
  src/layers/services/main.service.js
  src/sequelize/config/config.js
Labels: bug

#43 PR : Modify models/user.js
  src/sequelize/models/user.js
Labels: enhancement

#48 PR : Modify promise.js, Add review.js, reviewImage.js / Install passport package
  package-lock.json
  package.json
  src/layers/controllers/auth.controller.js
  src/passport/index.js
  src/passport/localStrategy.js
  src/sequelize/models/promise.js
  src/sequelize/models/review.js
  src/sequelize/models/reviewImage.js
Labels: add, feature

#60 PR : Feature/deploy
  appspec.yml
  scripts/after-deploy.sh
  src/sequelize/config/config.js
  src/sequelize/models/session.js
Labels: add, feature

#65 Modify for code deploy
  .gitignore
  .sequelizerc
  appspec.yml
  package-lock.json
  package.json
  scripts/after-deploy.sh
  src/sequelize/config/config.js
  src/sequelize/models/index.js
Labels: enhancement, add

#68 deploy test1
  package.json
  scripts/after-deploy.sh
  src/app.js
  src/sequelize/models/index.js
Labels: bugfix

#69 deploy test2
  package.json
Labels: enhancement

#70 에러 해결
  package.json
  scripts/after-deploy.sh
  src/app.js
  src/layers/controllers/review.controller.js
  src/sequelize/models/index.js
Labels: bugfix

#73 에러수정 2차
  src/layers/controllers/review.controller.js
Labels: bugfix

#76 enhance promise related api
  package-lock.json
  src/layers/controllers/main.controller.js
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
  src/sequelize/models/user.js
Labels: add

#77 Update and modify: promise related api
  package-lock.json
  src/layers/controllers/main.controller.js
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
  src/sequelize/models/user.js
Labels: add

#79 modify promise.repository getAllPromise from Friend to User
  package.json
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
  src/sequelize/config/config.js
Labels: add

#80 modify promise.service API 명세에 따라 friendList에 이름만 제공
  src/layers/services/promise.service.js
Labels: bugfix

#81 modify promise.service API 명세에 따라 friendList에 이름만 제공
  .vscode/launch.json
  package.json
  src/layers/controllers/main.controller.js
  src/layers/controllers/promise.controller.js
  src/layers/controllers/review.controller.js
  src/layers/middlewares/deleteImage.middleware.js
  src/layers/middlewares/image.middleware.js
  src/layers/repositories/promise.repository.js
  src/layers/repositories/review.repository.js
  src/layers/routers/review.router.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/layers/services/review.service.js
  src/sequelize/config/config.js
Labels: bugfix

#82 modify promise detail to match api
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add

#83 Modify promise detail to match api
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: bugfix

#86 PR : 민선님 용의님 나 작업 합쳐서 배포하기
  appspec.yml
  package.json
  scripts/after-deploy.sh
  src/layers/controllers/promise.controller.js
Labels: bugfix

#98 modify getAllPromise: 생성한 약속들만 볼 수 있게 수정
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/promise.service.js
Labels: feature

#99 modify getAllPromise: 생성한 약속들만 볼 수 있게 수정
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/promise.service.js
Labels: add

#102 delete constructor promise.controller/service && main branch update
  src/layers/controllers/promise.controller.js
  src/layers/services/promise.service.js
Labels: add

#103 update promise controller
  src/layers/controllers/promise.controller.js
  src/layers/services/promise.service.js
Labels: add

#104 Modify morgan formmat, Modify user model
  src/app.js
  src/sequelize/models/user.js
Labels: modify

#105 Modify morgan formmat, Modify user model
  src/app.js
  src/sequelize/models/user.js
Labels: modify

#108 Modify DB and Joi for x,y and penalty
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
Labels: bugfix

#109 Modify DB and Joi for x,y and penalty
  loadtest.json
  package-lock.json
  package.json
  src/layers/controllers/review.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/repositories/review.repository.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/layers/services/review.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
Labels: add, bugfix

#116 Fix promise.js
  .github/ISSUE_TEMPLATE/new-feature-.md
  src/layers/controllers/promise.controller.js
  src/sequelize/models/promise.js
Labels: bugfix

#118 Modify promise.js, user.js
  src/sequelize/models/promise.js
  src/sequelize/models/user.js
Labels: enhancement

#120 modify review model
  models/index.js
  src/sequelize/models/review.js
  src/sequelize/models/user.js
Labels: enhancement

#121 Modify promise model && Modify getAllPromise
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/promise.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
Labels: add

#122 Modify Promise model & modify getAllPromise
  models/index.js
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
  src/layers/services/promise.service.js
  src/modules/joiStorage.js
  src/sequelize/models/promise.js
  src/sequelize/models/review.js
  src/sequelize/models/user.js
Labels: add

#129 Add getMyPage API
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/auth.router.js
  src/layers/services/auth.service.js
Labels: add

#130 Add getMyPage API
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/auth.router.js
  src/layers/services/auth.service.js
Labels: add

#131 modify getPromiseDetail to add username
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add

#132 modify getPromiseDetail to add username
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add

#137 modify promise related error handling
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add, bugfix

#138 modify promise related error handling
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add, bugfix

#143 Modify find friend
  src/layers/controllers/promise.controller.js
  src/layers/repositories/promise.repository.js
  src/layers/services/promise.service.js
Labels: add

#144 Modify findFriend
  src/layers/controllers/promise.controller.js
  src/layers/controllers/review.controller.js
  src/layers/middlewares/deleteImage.middleware.js
  src/layers/repositories/promise.repository.js
  src/layers/repositories/review.repository.js
  src/layers/services/promise.service.js
  src/layers/services/review.service.js
  src/sequelize/models/review.js
Labels: add

#146 modify findFriend from substring to startsWith
  src/layers/repositories/promise.repository.js
Labels: add

#150 modify 약속 생성시 친구 추가 안되는 버그 해결
  src/layers/services/promise.service.js
Labels: bugfix

#151 modify 약속 생성시 친구 추가 안되는 버그 해결
  src/layers/services/promise.service.js
Labels: bugfix

#160 카카오 로그인 구현
  babel.config.json
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/auth.middleware.js.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/image.middleware.js.html
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  loadtest.json
  loadtest/loadtest.json
  loadtest/myReport
  loadtest/myReport.html
  loadtest/reviewdata.csv
  package-lock.json
  package.json
  src/db-init.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/promise.controller.js
  src/layers/middlewares/auth.middleware.js
  src/layers/middlewares/deleteImage.middleware.js
  src/layers/middlewares/image.middleware.js
  src/layers/repositories/promise.repository.js
  src/layers/routers/auth.router.js
  src/layers/routers/index.js
  src/layers/routers/promise.router.js
  src/layers/services/auth.service.js
  src/layers/services/main.service.js
  src/layers/services/promise.service.js
  src/layers/services/review.service.js
  src/modules/swagger.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/sequelize/models/user.js
  test/authmiddleware.test.js
  test/imagemiddleware.test.js
  test/review.repository.test.js
  test/review.service.test.js
Labels: feature

#163 프로미스 라우터 주석 해제
  src/layers/routers/promise.router.js
Labels: add

#171 modify 약속 상세 유저 닉네임 불러오기
  package.json
  src/layers/repositories/promise.repository.js
Labels: modify

#172 modify 약속 상세 유저 실명에서 닉네임으로 변경
  src/layers/repositories/promise.repository.js
  src/layers/routers/promise.router.js
Labels: modify

#183 userId random apply, kakao image store
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
  src/passport/kakaoStrategy.js
  src/sequelize/models/user.js
Labels: enhancement

#184 userId random apply, kakao image store
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
  src/passport/kakaoStrategy.js
  src/sequelize/models/user.js
Labels: enhancement
